repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        language_version: python3.12

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args:
          [
            "--config=pyproject.toml",
            "--strict",
            "--show-error-codes",
            "--pretty",
          ]
        additional_dependencies:
          - pydantic>=2.7
          - pydantic-core>=2.18
        files: ^app/

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/mxab/pre-commit-trivy
    rev: v0.15.0
    hooks:
      - id: trivyconfig-docker
        args: [--exit-code, "1", "--skip-dirs", ".venv"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: cyclonedx-python
        name: CycloneDX SBOM (Python)
        entry: cyclonedx-py -o sbom-python.xml --format xml
        language: system
        types: [python]
        stages: [manual]
