from typing import Protocol


class StoragePort(Protocol):
    """Абстрактный порт хранилища файлов."""

    async def save(self, content: bytes, filename: str) -> str: ...
    async def load(self, file_id: str) -> bytes: ...
    async def delete(self, file_id: str) -> None: ...
    def is_healthy(self) -> bool: ...
