name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Cache Poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-${{ runner.os }}-

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Ruff
        run: ruff .

      - name: Mypy
        run: mypy --strict app
        working-directory: ${{ github.workspace }}

      - name: Tests
        run: pytest -q --cov=app --cov-fail-under=90 --cov-report=xml

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          load: true
          build-args: |
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
          tags: ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}

      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}
          scan-type: image
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: SBOM (cyclonedx-python)
        run: |
          pip install cyclonedx-bom
          cyclonedx-py -o sbom-python.xml --format xml

      - name: SBOM (syft)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}
          artifact-name: sbom-image.spdx.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            sbom-python.xml
            sbom-image.spdx.json
            trivy-results.sarif

  publish:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/docuscope:latest
            ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}

      - name: Trivy scan (pushed)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}
          scan-type: image
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL

      - name: SBOM (syft)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository_owner }}/docuscope:${{ github.sha }}
          artifact-name: sbom-image.spdx.json

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifacts
          path: |
            sbom-image.spdx.json
            trivy-results.sarif
